### ISSUE TITLE
Running countly-server in Windows mode, the first request to create an application is 404

### ISSUE THREAD

**Issue by DyncKathline** [Countly/countly-server#1018]
I was running with node app. js after using IDE to modify Windows. I can create users and see them in MongoDB. But when I click the Create button, prompt 404, I don't know how to associate plug-ins.
### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/16282974/62834374-c2676280-bc7d-11e9-80aa-4495d7bcacc8.png)

### More Description
http://192.168.56.1:6001/i/apps/create 404

### Your Environment
window10

**Comment by ar2rsawseen** [comment]
Hello,
Countly has 2 main processes
app.js and api.js

api.js is the main backend API

and app.js is just dashboard that communicates through backend API.

You are able to create first user, as it is done through app.js
but the rest actions that require API will fail with 404, because you don't have API process running,

**Comment by DyncKathline** [comment]
I ran api. js and it still works the same way, showing 404
![image](https://user-images.githubusercontent.com/16282974/62844165-fa0ff200-bcf1-11e9-92b1-08e4a7a4e123.png)

**Comment by ar2rsawseen** [comment]
In overall, Countly is not meant to be run that way.
Now dashboard sends requests to /i/some/endpoint which does not exist, because in usual setup, nginx is the one who processes requests based on path and sends it to appropriate process.

I guess, you could try editing here:
https://github.com/Countly/countly-server/blob/master/frontend/express/public/javascripts/countly/countly.config.sample.js#L13

To set it to localhost:3001 so it would reach api.js process without nginx, but I am not sure if there are any other problems further or not.

**Comment by DyncKathline** [comment]
I try to edit here:
Https://github.com/countly/countly-server/blob/master/frontend/express/public/javascripts/countly/countly.config.sample.js L13

But it didn't work. Actually, the object countlyGlobal used express/config.js path in express/app.js, but I used express/config.js path, but it didn't work, I don't know if it was right.
![image](https://user-images.githubusercontent.com/16282974/62851210-f98a5200-bd17-11e9-9b57-4103c1677521.png)

**Comment by ar2rsawseen** [comment]
No, I mean in your system, after installing Countly, you should have file like countly/frontend/express/public/javascripts/countly/countly.config.js

And there, for the value `countlyCommon.API_URL` provide localhost:3001

Like this:
```
countlyCommon.API_URL = "localhost:3001";
```

But as I said, in overall we don't support running Countly like that and there may be more other problems to solve, for which we can't provide support.

**Comment by DyncKathline** [comment]
I used it, but cross-domain, how to solve it?
![image](https://user-images.githubusercontent.com/16282974/62852044-d9a85d80-bd1a-11e9-9baa-7157b0d999b0.png)

**Comment by DyncKathline** [comment]
Thank you.Change it to countlyCommon.API_URL = "http://locahost:3001";I can access it.
