### ISSUE TITLE
error~15.03

### ISSUE THREAD

**Issue by zynbasil** [Countly/countly-server#136]
[TypeError: Cannot read property 'name' of undefined]
[TypeError: Cannot read property 'name' of undefined]
[TypeError: Cannot read property 'name' of undefined]
[TypeError: Cannot read property 'name' of undefined]
[TypeError: Cannot read property 'name' of undefined]
[TypeError: Cannot read property 'name' of undefined]

/home/zynbasil/Desktop/countly/api/node_modules/mongoskin/lib/utils.js:33
  var skinClassName = 'Skin' + NativeClass.name;
                                          ^
[TypeError: Cannot read property 'name' of undefined]
[TypeError: Cannot read property 'name' of undefined]
TypeError: Cannot read property 'name' of undefined

Help!!!!~~~~~~~~~~~

**Comment by kithokit** [comment]
How to solve this i also made this problem

**Comment by kithokit** [comment]
I have checkout the tags 15.03 , then make a fresh installation

**Comment by ar2rsawseen** [comment]
This issue was already fixed in github 
https://github.com/Countly/countly-server/commit/9ac4122dcdd306597b098b413b3293f8abc3a3bf
and will be fixed in next release

The steps you can take to fix it can be found here:
http://support.count.ly/discussions/problems/3917-failure-after-upgrade

I will leave this issue open until we get the new release out

**Comment by ar2rsawseen** [comment]
Closing this issue since we already released
