### ISSUE TITLE
SDK for other languages?

### ISSUE THREAD

**Issue by windware-ono** [Countly/countly-server#1532]
I see there's node.js SDK to be used on the server side for error logging but are there any plans for other languages like PHP?
There is a document describing how to communicate with the server for error logging but should I just use that?

**Comment by ar2rsawseen** [comment]
Hello
SDK availability usually depends on how many requests we receive for a certain language/environment. There is currently a set of core SDKs we develop ourselves and the rest are community-based where some external 3rd party developers develop SDK for their needs.

For PHP, I think this is the first time someone requests it. Mostly because it does not really make much sense to use Analytics SDK in the backend. Although it is possible, such use cases are really rare. In most cases, it is just enough to make 1 or 2 direct API calls yourself, without SDK.

For example, Nodejs SDK exists for 2 purposes: 
1) Running it on devices in IoT like scenarios (where basically devices/servers are your users and not end-users)
2) Doing bulk data migrations or server data enrichments with CountlyBulk Class

But in overall, SDKs communicate through this API endpoint:
https://api.count.ly/reference#i

And overall SDK behavior is described here:
https://support.count.ly/hc/en-us/articles/360037753291-SDK-development-guide

In theory, you could use server cookies to track user sessions on the server-side too, etc, but as I said, the use case for these are really rare.

Maybe you can share your use case? :)

**Comment by windware-ono** [comment]
What I'm trying to accomplish is do error logging and event logging on the server side for a web app and not just for the frontend errors and activities.

I see there are plenty of competitors on error logging like Sentry which comes with many server side languages SDK support but I couldn't use Countly to do server side logging except for node.js.

For instance, uncaught exceptions or intentional error logging on the server side (say, DB wasn't reachable etc).
I really don't want to separate error logging to another tool because a language isn't supported.

**Comment by ar2rsawseen** [comment]
So here, the main question would be, how would you tie that data together to the user on frontend? Because you would need to use the same device_id as on frontend when making requests for that user on the backend.
Or you would not and it would simply be a separate app in Countly dashboard?

Overall, as I said, there is no SDK yet, bu, yes, this should be possible, you could use set_error_handler() in PHP and inside it makes requests to the server directly via the provided endpoint reporting events and errors.

**Comment by windware-ono** [comment]
I don't mean to relate server side errors to specific users but say the conversion goes down at a certain time in a day, I can go narrow down the error reporting from the server side to the time and if I see many errors saying DB was unreachable, then I can see what had happened instead of just the browser's errors that can't tell anything really specific on server side errors.

Yes, if there is no SDK, the only way to do is make API request manually but was hoping it could have SDK for easier integration.

**Comment by windware-ono** [comment]
Also server side events become handy, when, say, I want to synchronize stock counts on various e-commerce sites which has nothing to do with the frontend, but when someone purchases an item, I can also log that synchronization took place on each targets on the server side and I can easily see anomalies if such knowledge is available in the Countly interface.

**Comment by ar2rsawseen** [comment]
We are doing market research on SDKs and based on that SDK decisions will be made
Adding @ArtursKadikis for noting this request, but overall, no promises, we cannot support all languages :)
