### ISSUE TITLE
Find app_user once per API call

### ISSUE THREAD

**Issue by iartem** [Countly/countly-server#158]
Right now a lot of plugins look for app user on their own. This produces a lot of the same DB requests per one API request. It should be possible to look for api_user once in plugin manager.

**Comment by ar2rsawseen** [comment]
true, been thinking on that too

since app_user only makes sense in SDK call context, and all SDK calls go through validateAppForWriteAPI method, we probably can query app_user there and add it to params object (same as with app data), so all plugins could get it from there

**Comment by ar2rsawseen** [comment]
The only downside for that is that some api calls may not require app_user data (like when submitting event I think) and query would be wasted.

So my other option was to implement lazy loader, first one needs it loads it and other get it from params object, but since it is a single request thing, they would probably simply perform a query all in paralel :)

**Comment by iartem** [comment]
Well, it’s like 5-10 or even more same queries on EE per begin / end session and duration API calls right now. I think we can easily sacrifice one request in event case for the sake of all others. :)

**Comment by ar2rsawseen** [comment]
agreed

**Comment by ar2rsawseen** [comment]
Not completely like that but we ended up having single point of update/read for app_users, which improves speed, cause there are no anymore needless reads for app_users

**Comment by gorkem-cetin** [comment]
Is there a speed comparison btw?

**Comment by ar2rsawseen** [comment]
We did some comparison yes, and there is slight improvement, but not much
