### ISSUE TITLE
Mongodb 20.11 upgrade script fails

### ISSUE THREAD

**Issue by systemaddict** [Countly/countly-server#1663]
I've the community edition running (v. 20.04 - installed via DigitalOcean 1-click) and tried the mongodb upgrade script to 20.11.

The upgrade.mongo.40.sh fails with "Invalid command argument." (the output says that system is updated to 4.0 but mongo is still at old version 3.6.8:

MongoDB shell version v3.6.8
connecting to: mongodb://127.0.0.1:27017/admin
MongoDB server version: 3.6.8
{ "featureCompatibilityVersion" : { "version" : "3.6" }, "ok" : 1 }
MongoDB shell version v3.6.8
connecting to: mongodb://127.0.0.1:27017/admin
MongoDB server version: 3.6.8
{ "featureCompatibilityVersion" : { "version" : "3.6" }, "ok" : 1 }
MongoDB shell version v3.6.8
connecting to: mongodb://127.0.0.1:27017/admin
MongoDB server version: 3.6.8
{
"ok" : 0,
"errmsg" : "Invalid command argument. Expected '3.6' or '3.4', found 4.0 in: { setFeatureCompatibilityVersion: \"4.0\", $db: \"admin\" }. See http://dochub.mongodb.org/core/3.6-feature-compatibility.",
"code" : 2,
"codeName" : "BadValue"
}
Upgraded MongoDB to 4.0

**Comment by kaanklky** [comment]
MongoDB packages are in held state on DigitalOcean image so the script can't remove MongoDB 3.6 by `apt-get remove` command. Please run `mongo admin --eval 'db.adminCommand( { setFeatureCompatibilityVersion: "3.6" } )'` first then add `--allow-change-held-packages` at the end of the command at line 54 in `upgrade.mongodb.40.sh` & run script again. You don't need to do same changes for `upgrade.mongodb.42.sh` or `upgrade.mongodb.44.sh` since newly installed packages will not be held.
