### ISSUE TITLE
Links are shown wrong in analytics

### ISSUE THREAD

**Issue by gugmaster** [Countly/countly-server#207]
Links are not shown correctly.

Instead of http:// they get http.// 

http.//www.softsurroundings.com/home/

**Comment by gugmaster** [comment]
![screen shot 2015-10-19 at 12 09 11](https://cloud.githubusercontent.com/assets/1446373/10575065/4eacb88a-765a-11e5-90be-76d946f27d1a.png)

**Comment by ar2rsawseen** [comment]
Hello, is this for events?
Are you using Countly Web SDK?

**Comment by gugmaster** [comment]
Hi Artur,

> Am 19.10.2015 um 21:23 schrieb Arturs Sosins <notifications@github.com>:
> 
> Hello, is this for events?
> 
Yes.

> Are you using Countly Web SDK?
> 

This happened to me when I am sending URLs from iOS app to Countly (event). I tracked it down and found out that the URL
was going out the correct way from the iOS SDK (request). So I suspect that the error happens in Countly Server. 

I would like to fix the issue but I am not sure when I have time.

Best regards,
Stefan

**Comment by ar2rsawseen** [comment]
well sure, I know why this happens, unfortunately the fix is not that easy, due to all previously saved information.

Problem is that some symbols (like dots) cannot be stored in mongodb as keys, so they are replaced by other symbols (like colons) and then replaces back before displaying them (that's when http: becomes http.).

I had similar problem with source plugin, where I encoded and decoded dots differently, unfortunately it is really hard to do it whole Countly wide, because of the previously stored information which was already stored in replaced symbol way. (when displaying info back we won't know which was encoded by replacing symbol and which by escaping it)

for now suggestion would be to use domain without protocol, but we are thinking on more appropriate solution for this problem as it will soon become more popular with more Web Analytics usage

**Comment by ar2rsawseen** [comment]
Fixed here:
https://github.com/Countly/countly-server/commit/7038f0bb7d6dde9f41414b1406c540168145dd3c
