### ISSUE TITLE
Single user is counted as two somehow.

### ISSUE THREAD

**Issue by kayone** [Countly/countly-server#240]
I'm really starting to question our use of countly, I just don't understand how can something this critical/obvious not have been caught before,

`i?app_key=xxx0&device_id=test_device&begin_session=1&ip_address=192.168.1.111&metrics={%22_os%22:%22Windows%22,%22_os_version%22:%226.1%22,%22_app_version%22:%221.0.0.0%22,%22_store%22:%22Single%20device%22}`

That's a single metric, from a single user, yet in a bunch of places in the dashboard it shows as two,

![image](https://cloud.githubusercontent.com/assets/412280/13557162/ee027f1c-e39e-11e5-84f4-c64d43d1febf.png)

![image](https://cloud.githubusercontent.com/assets/412280/13557164/0861d83a-e39f-11e5-9a84-a894a9b7205b.png)

![image](https://cloud.githubusercontent.com/assets/412280/13557169/17777fd2-e39f-11e5-82c3-5ad07fe2a141.png)

**Comment by osoner** [comment]
Right now Countly has an estimation algorithm for total users calculation for periods other than this year, month, today and yesterday. We need this because we store this data daily, weekly and monthly. Something that looks very much like this;

    {
        2015: {
            7: { // month, July
                u: 1 // total user count for the month
                23: { // 23 July
                    u: 1 // total user count for the day
                },
                24: {
                    u: 1
                }
            },
            w30: { // week 30 of the year
                u: 1 // total user count for the day
            }
        }
    }
    
When you select 7 days from Countly UI, the first thing we do is to find the biggest time buckets we have the data for. For example if the 7 days corresponds to 19 July to 25 July, the biggest buckets are 19 July and week 30 (2015.7.19 and 2015.w30). 

Another example: you select 30 days from Countly UI and this corresponds to lets say 30 June to 30 July. This time biggest buckets available are 30 June and July altogether (2015.6.30 and 2015.7).

**Step 1:** After finding the biggest buckets the next step is to sum all `u` properties to get to our first total user estimation.

**Step 2:** Next step is finding a "correction period", a bigger set of time buckets that you can compare your finding to. For the above 7 days example, bigger buckets are week 29 and week 30. For the 30 day example those are week 27 and July. We replay the same step here, finding the total user count for these correction period buckets.

Lastly we check if what we found in step 2 is less than step 1. If so we use our findings from step 2.

This estimation applies only to "total users" calculation in everywhere you see on Countly UI.

We are currently working on a mechanism that will get rid of estimation for any period that includes today. Basically exact number of users will be shown for 7 days, 30 days, 60 days and any period that contains today. There is a performance implication that comes with this fix and we are currently trying to minimise it.

**Comment by ar2rsawseen** [comment]
Should be fixed for period including today in
https://github.com/Countly/countly-server/commit/672d793caa2b057ac25d00dbb61a1a60e2d13d99
