### ISSUE TITLE
Why Event logs only has 1000 record?

### ISSUE THREAD

**Issue by littleto** [Countly/countly-server#337]
while I want to explore this item ,finding that 1 to 50 in 1000 items on the bottom of the page.where are the others logs store?How can I find all the logs>

**Comment by gorkem-cetin** [comment]
Event logs is not meant to store logs forever but it is used to debug your SDKs. Hence we dont store more than 1000 items. If you want to retrieve data from Countly you should be using our APIs (https://resources.count.ly/reference)

**Comment by littleto** [comment]
okay,thanks.

**Comment by MrRRcc** [comment]
Respected.
Is it that countly community edition has 1000 records limit of log{api_id} tables ?
I have build countly community edition 17.05.1 and I encountered the problem that all log{api_id} have only last 1000 records.How could I save all records?

**Comment by ar2rsawseen** [comment]
As @gorkem-cetin elaborated, 1000 is a nice limit, allowing you to debug latest request, and not overflowing your database with too much data.
You can disable it by removing cap from logs collection, but it would both grow in quite large disk space usage, and writes would eventually become too slow because of too much data and it would hurt your instance performance wise.
If you are still up for it, there is no way to "uncap" collection, so you just have to drop it. After that, new incoming data would create collection again and it wont be capped, and thus would store all the data. But as I said, this is not advised.

**Comment by MrRRcc** [comment]
Thank you for your advice , now I know how to deal with my question.~@ar2rsawseen
