### ISSUE TITLE
The service is loaded very slowly

### ISSUE THREAD

**Issue by yaoboxu** [Countly/countly-server#342]
![slower](https://user-images.githubusercontent.com/32385205/32152551-b4313b38-bd5f-11e7-9f7f-a0f82aa559cd.png)

**Comment by ar2rsawseen** [comment]
Hello,
is it possible for you to identify which request is that long one?
When I try, it all loads pretty relatively quickly.
We experienced before something similar, when Google services were enabled for Chinese clients, but now I rechecked and on asia-try.count.ly it is disabled, so maybe we missed some bits somewhere, that's why it would help if you could identify that long request

**Comment by MrRRcc** [comment]
just set Management-Configurations-Frontend-Use Google Services disable

**Comment by gorkem-cetin** [comment]
Closing this issue @yaoboxu - if you have more information about this issue, let us know.
