### ISSUE TITLE
using expressjs in api

### ISSUE THREAD

**Issue by oroce** [Countly/countly-server#53]
Is there any reason not to use expressjs in api?

It would be nice to use because:
* easier read
* easier to maintain
* frontend could mount the api, so countly could be deployed without any proxy

**Comment by ar2rsawseen** [comment]
The main concern was and is performance. Due to high load of data our users have, api must be as efficient as possible. And some test show that express.js is quite inefficient: https://raygun.io/blog/2015/02/node-js-performance-node-js-vs-io-js/

Plus since plugins branch, plugin mechanism is quite deeply integrated with current api structure, so for now I don't see that we would rewrite api to express.js in near future
