### ISSUE TITLE
Fonts are hideously ugly at the default zoom level

### ISSUE THREAD

**Issue by a20eac1d** [Countly/countly-server#549]
The fonts used by Countly (Ubuntu) are being rendered unsharp / corny at the default zoom level.

(see screenshot 1)

What I mean by unsharp are those little pixels that are added or missing in the rendered text. They are only visible at certain zoom levels. If I use my browser to zoom in the webpage to 125% they become smooth again:

(see screenshot 2)

### Expected Behavior
Use a font that behaves correctly at all scaling settings

### Current Behavior
The font is not smooth at all and looks very unprofessional. Some text is even hard to read.

### Screenshots (if appropriate):
(1) https://i.imgur.com/ILIFlru.png
(2) https://i.imgur.com/J4MGkG0.png

### Possible Solution
Use a font that handles zooming better. Maybe add the ability to switch fonts / upload custom fonts in the admin panel

### Steps to Reproduce (for bugs)
1. Use: Windows 8.1 + Chrome Version 67.0.3396.99 (64-Bit)
2. Set Windows DPI Scaling to "Medium 125%"
3. Open any Countly site

### More Description
The font looks extremely unprofessional and some items are hard to read

### Your Environment
Windows 8.1 Pro 64-bit
Version 67.0.3396.99 (64-Bit)
Countly Latest Version, installed by the c.ly bash installer

**Comment by kaanklky** [comment]
Hello @a20eac1d, I think this is because of application and/or operating system's font rendering but even so I tried to reprod your issue and I failed. I'm seeing the font great at %100 but it is lookslike bad at %125 zoom as in your first screenshot. I think it is because of Windows' font rendering as I said, so I recommend to try Windows' LCD Font Smoothing.
