### ISSUE TITLE
Drill Tab: Numeric data is interpreted as a date in filter

### ISSUE THREAD

**Issue by geak** [Countly/countly-server#594]
### Current Behavior
Numeric data (like 123456789) are interpreted as date (see screenshot).

### Screenshots (if appropriate):
![2018-08-08 1 13 45](https://user-images.githubusercontent.com/3874202/43802928-578f6d42-9aa8-11e8-89ce-2acfb060b429.png)

### Steps to Reproduce (for bugs)

0. Using Countly Android SDK
1. Send custom segments {"Key" : "Value"} (value has a type of String)
2. On Frontend this value is shown like a date

### Your Environment

* Android

**Comment by ar2rsawseen** [comment]
Hello,
yes this is done intentionally
countly does type check/conversion on server
and 10 and 13 length numbers are interpreted as timestamps and milisecond timestamps.

if yo want to keep it as string, prefix or postfix it with some characters

In future we might introduce more control over which property can have which type, but for now, this is expected behavior

**Comment by geak** [comment]
Thank you!
